# Generated by Django 4.2.5 on 2023-10-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_health', models.IntegerField(default=100)),
                ('ship_engine_level', models.IntegerField(default=1)),
                ('ship_shield_level', models.IntegerField(default=1)),
                ('ship_weapon_level', models.IntegerField(default=1)),
                ('player_hat', models.CharField(blank=True, max_length=200, null=True)),
                ('player_shirt', models.CharField(blank=True, max_length=200, null=True)),
                ('player_money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('show_hp', models.BooleanField(default=False)),
                ('sound', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('timeout', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SceneButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('hp_change', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('next_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_scene', to='adventures.scene')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.scene')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.player')),
            ],
        ),
    ]
