# Generated by Django 4.2.5 on 2023-10-04 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_questlines', models.ManyToManyField(blank=True, help_text='What questlines must be complete to make the questline available?', to='adventures.questline')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_hat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_money',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_shirt',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ship_engine_level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ship_shield_level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ship_weapon_level',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='quest_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='player_hat_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_hat_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_shirt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_shirt_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_scene_for_player', to='adventures.scene'),
        ),
        migrations.AddField(
            model_name='player',
            name='ship_engine_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_engine_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='ship_shield_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_shield_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='ship_weapon_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_weapon_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='timeout_next_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeout_prev_scene', to='adventures.scene'),
        ),
        migrations.AddField(
            model_name='scenebutton',
            name='item_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_button_add', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='scenebutton',
            name='item_remove',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_button_remove', to='adventures.item'),
        ),
        migrations.AlterField(
            model_name='inventoryrow',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.item'),
        ),
        migrations.AlterField(
            model_name='inventoryrow',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenebutton',
            name='next_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_btn_next_scene', to='adventures.scene'),
        ),
        migrations.CreateModel(
            name='ShopKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_scene_for_shop', to='adventures.scene')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_scene', to='adventures.scene')),
                ('scene_button', models.ForeignKey(blank=True, help_text='SceneButton to add to parent_scene which will show "scene"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_scene_button', to='adventures.scenebutton')),
            ],
        ),
        migrations.CreateModel(
            name='ShopInventoryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.shopkeeper')),
            ],
        ),
        migrations.CreateModel(
            name='QuestLineRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('questline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.questline')),
                ('scene_button', models.ForeignKey(blank=True, help_text='SceneButton to add to parent scene which will show "scene"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_button_for_quest', to='adventures.scenebutton')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerQuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.player')),
                ('quest_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.questlinerow')),
            ],
        ),
    ]
