# Generated by Django 4.2.5 on 2023-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_questline_remove_item_slug_remove_player_player_hat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
