# Generated by Django 4.2.5 on 2023-10-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_scene_timeout_next_scene'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_questlines', models.ManyToManyField(blank=True, help_text='What questlines must be complete to make the questline available?', to='adventures.questline')),
            ],
        ),
        migrations.CreateModel(
            name='QuestLineRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('parent_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_scene_for_quest', to='adventures.scene')),
                ('questline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.questline')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.scene')),
                ('scene_button', models.ForeignKey(blank=True, help_text='SceneButton to add to parent_scene which will show "scene"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_button_for_quest', to='adventures.scenebutton')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerQuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.player')),
                ('quest_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.questlinerow')),
            ],
        ),
    ]
