# Generated by Django 4.2.5 on 2023-10-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_questline_questlinerow_playerquestprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_hat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_money',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_shirt',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ship_engine_level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ship_shield_level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ship_weapon_level',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_hat_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_hat_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_shirt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_shirt_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='ship_engine_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_engine_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='ship_shield_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_shield_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='player',
            name='ship_weapon_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_weapon_item', to='adventures.item'),
        ),
        migrations.AddField(
            model_name='scenebutton',
            name='item_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.item'),
        ),
        migrations.AddField(
            model_name='scenebutton',
            name='item_remove',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_button_remove', to='adventures.item'),
        ),
        migrations.CreateModel(
            name='ShopKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_scene_for_shop', to='adventures.scene')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_scene', to='adventures.scene')),
                ('scene_button', models.ForeignKey(blank=True, help_text='SceneButton to add to parent_scene which will show "scene"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_scene_button', to='adventures.scenebutton')),
            ],
        ),
        migrations.CreateModel(
            name='ShopInventoryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.shopkeeper')),
            ],
        ),
    ]
