# Generated by Django 4.2.5 on 2023-10-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_remove_player_player_hat_remove_player_player_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='questline',
            name='slug',
        ),
    ]
