# Generated by Django 4.2.5 on 2023-10-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_remove_item_slug_remove_questline_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questlinerow',
            name='parent_scene',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questlinerow',
            name='scene_button',
            field=models.ForeignKey(blank=True, help_text='SceneButton to add to parent scene which will show "scene"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_button_for_quest', to='adventures.scenebutton'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
