# Generated by Django 4.2.5 on 2023-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0006_scene_timeout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='timeout_type',
            field=models.CharField(blank=True, choices=[('engine', 'Engine'), ('weapon', 'Weapon'), ('building', 'Building')], default='building', max_length=200, null=True),
        ),
    ]
