# Generated by Django 4.2.5 on 2023-10-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0007_remove_questlinerow_scene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questlinerow',
            name='scene_button',
        ),
        migrations.AddField(
            model_name='scenebutton',
            name='questline_row',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.questlinerow'),
        ),
    ]
