# Generated by Django 4.2.5 on 2023-10-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0008_remove_questlinerow_scene_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenebutton',
            name='questline_row',
        ),
        migrations.AddField(
            model_name='questlinerow',
            name='scene_button',
            field=models.ForeignKey(blank=True, help_text='SceneButton to add to parent scene which will show "scene"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_button_for_quest', to='adventures.scenebutton'),
        ),
    ]
