# Generated by Django 4.2.5 on 2023-10-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0008_scene_apriltag'),
    ]

    operations = [
        migrations.AddField(
            model_name='questlinerow',
            name='show_until',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Näytä kunnes pelaaja on tehnyt kohdan X'),
        ),
    ]
