# Generated by Django 4.2.5 on 2023-10-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0009_questlinerow_show_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_root_scene',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
