# Generated by Django 4.2.5 on 2023-10-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0010_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerquestprogress',
            name='quest_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.questlinerow'),
        ),
        migrations.AlterField(
            model_name='scenebutton',
            name='next_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_btn_next_scene', to='adventures.scene'),
        ),
    ]
