# Generated by Django 4.2.5 on 2023-10-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0012_playerquestprogress_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerquestprogress',
            name='quest_row',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adventures.questlinerow'),
            preserve_default=False,
        ),
    ]
