# Generated by Django 4.2.5 on 2023-10-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0013_alter_playerquestprogress_quest_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quest_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scenebutton',
            name='item_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_button_add', to='adventures.item'),
        ),
    ]
