# Generated by Django 4.2.5 on 2023-10-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0014_item_quest_item_alter_scenebutton_item_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='previous_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_scene_for_player', to='adventures.scene'),
        ),
        migrations.AlterField(
            model_name='inventoryrow',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_hat_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_hat_item', to='adventures.item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_shirt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_shirt_item', to='adventures.item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ship_engine_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_engine_item', to='adventures.item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ship_shield_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_shield_item', to='adventures.item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ship_weapon_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_weapon_item', to='adventures.item'),
        ),
        migrations.AlterField(
            model_name='questlinerow',
            name='scene_button',
            field=models.ForeignKey(blank=True, help_text='SceneButton to add to parent scene which will show "scene"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_button_for_quest', to='adventures.scenebutton'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='timeout_next_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeout_prev_scene', to='adventures.scene'),
        ),
        migrations.AlterField(
            model_name='scenebutton',
            name='item_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_button_add', to='adventures.item'),
        ),
        migrations.AlterField(
            model_name='scenebutton',
            name='item_remove',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_button_remove', to='adventures.item'),
        ),
        migrations.AlterField(
            model_name='scenebutton',
            name='next_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_btn_next_scene', to='adventures.scene'),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='parent_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_scene_for_shop', to='adventures.scene'),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_scene', to='adventures.scene'),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='scene_button',
            field=models.ForeignKey(blank=True, help_text='SceneButton to add to parent_scene which will show "scene"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_scene_button', to='adventures.scenebutton'),
        ),
    ]
